#!/bin/sh
wget http://www.manythings.org/anki/afr-eng.zip -O Afrikaans_English_717.zip
wget http://www.manythings.org/anki/sqi-eng.zip -O Albanian_English_412.zip
wget http://www.manythings.org/anki/arq-eng.zip -O AlgerianArabic_English_157.zip
wget http://www.manythings.org/anki/ara-eng.zip -O Arabic_English_10842.zip
wget http://www.manythings.org/anki/aze-eng.zip -O Azerbaijani_English_2091.zip
wget http://www.manythings.org/anki/eus-eng.zip -O Basque_English_665.zip
wget http://www.manythings.org/anki/bel-eng.zip -O Belarusian_English_2594.zip
wget http://www.manythings.org/anki/ben-eng.zip -O Bengali_English_4400.zip
wget http://www.manythings.org/anki/ber-eng.zip -O Berber_English_36962.zip
wget http://www.manythings.org/anki/bul-eng.zip -O Bulgarian_English_14975.zip
wget http://www.manythings.org/anki/yue-eng.zip -O Cantonese_English_3129.zip
wget http://www.manythings.org/anki/cat-eng.zip -O Catalan_English_639.zip
wget http://www.manythings.org/anki/ceb-eng.zip -O Cebuano_English_176.zip
wget http://www.manythings.org/anki/dtp-eng.zip -O CentralDusun_English_1465.zip
wget http://www.manythings.org/anki/cbk-eng.zip -O Chavacano_English_1904.zip
wget http://www.manythings.org/anki/cmn-eng.zip -O Chinese_Mandarin_English_20302.zip
wget http://www.manythings.org/anki/chv-eng.zip -O Chuvash_English_195.zip
wget http://www.manythings.org/anki/hrv-eng.zip -O Croatian_English_1245.zip
wget http://www.manythings.org/anki/ces-eng.zip -O Czech_English_8561.zip
wget http://www.manythings.org/anki/dan-eng.zip -O Danish_English_16085.zip
wget http://www.manythings.org/anki/nld-eng.zip -O Dutch_English_28524.zip
wget http://www.manythings.org/anki/est-eng.zip -O Estonian_English_1550.zip
wget http://www.manythings.org/anki/fin-eng.zip -O Finnish_English_53407.zip
wget http://www.manythings.org/anki/fra-eng.zip -O French_English_160538.zip
wget http://www.manythings.org/anki/glg-eng.zip -O Galician_English_125.zip
wget http://www.manythings.org/anki/kat-eng.zip -O Georgian_English_147.zip
wget http://www.manythings.org/anki/deu-eng.zip -O German_English_174987.zip
wget http://www.manythings.org/anki/ell-eng.zip -O Greek_English_14496.zip
wget http://www.manythings.org/anki/heb-eng.zip -O Hebrew_English_126144.zip
wget http://www.manythings.org/anki/hin-eng.zip -O Hindi_English_2866.zip
wget http://www.manythings.org/anki/hun-eng.zip -O Hungarian_English_61305.zip
wget http://www.manythings.org/anki/isl-eng.zip -O Icelandic_English_6659.zip
wget http://www.manythings.org/anki/ilo-eng.zip -O Ilocano_English_1694.zip
wget http://www.manythings.org/anki/ind-eng.zip -O Indonesian_English_6754.zip
wget http://www.manythings.org/anki/ita-eng.zip -O Italian_English_310697.zip
wget http://www.manythings.org/anki/jpn-eng.zip -O Japanese_English_42992.zip
wget http://www.manythings.org/anki/kab-eng.zip -O Kabyle_English_6571.zip
wget http://www.manythings.org/anki/kan-eng.zip -O Kannada_English_150.zip
wget http://www.manythings.org/anki/pam-eng.zip -O Kapampangan_English_1185.zip
wget http://www.manythings.org/anki/kha-eng.zip -O Khasi_English_645.zip
wget http://www.manythings.org/anki/khm-eng.zip -O Khmer_English_474.zip
wget http://www.manythings.org/anki/kor-eng.zip -O Korean_English_778.zip
wget http://www.manythings.org/anki/lvs-eng.zip -O Latvian_English_714.zip
wget http://www.manythings.org/anki/lit-eng.zip -O Lithuanian_English_2059.zip
wget http://www.manythings.org/anki/nds-eng.zip -O LowSaxon_English_3263.zip
wget http://www.manythings.org/anki/mkd-eng.zip -O Macedonian_English_62553.zip
wget http://www.manythings.org/anki/zsm-eng.zip -O Malay_English_134.zip
wget http://www.manythings.org/anki/mal-eng.zip -O Malayalam_English_557.zip
wget http://www.manythings.org/anki/mri-eng.zip -O Maori_English_203.zip
wget http://www.manythings.org/anki/mar-eng.zip -O Marathi_English_33535.zip
wget http://www.manythings.org/anki/nst-eng.zip -O Naga_Tangshang_English_307.zip
wget http://www.manythings.org/anki/max-eng.zip -O NorthMoluccanMalay_English_176.zip
wget http://www.manythings.org/anki/nob-eng.zip -O Norwegian_Bokmål_English_5645.zip
wget http://www.manythings.org/anki/pes-eng.zip -O Persian_English_1956.zip
wget http://www.manythings.org/anki/pol-eng.zip -O Polish_English_37395.zip
wget http://www.manythings.org/anki/por-eng.zip -O Portuguese_English_132817.zip
wget http://www.manythings.org/anki/ron-eng.zip -O Romanian_English_8213.zip
wget http://www.manythings.org/anki/rus-eng.zip -O Russian_English_324680.zip
wget http://www.manythings.org/anki/srp-eng.zip -O Serbian_English_10569.zip
wget http://www.manythings.org/anki/slk-eng.zip -O Slovak_English_576.zip
wget http://www.manythings.org/anki/slv-eng.zip -O Slovenian_English_297.zip
wget http://www.manythings.org/anki/spa-eng.zip -O Spanish_English_119936.zip
wget http://www.manythings.org/anki/swe-eng.zip -O Swedish_English_17395.zip
wget http://www.manythings.org/anki/tgl-eng.zip -O Tagalog_English_3146.zip
wget http://www.manythings.org/anki/tam-eng.zip -O Tamil_English_197.zip
wget http://www.manythings.org/anki/tat-eng.zip -O Tatar_English_528.zip
wget http://www.manythings.org/anki/tel-eng.zip -O Telugu_English_138.zip
wget http://www.manythings.org/anki/tha-eng.zip -O Thai_English_111.zip
wget http://www.manythings.org/anki/tur-eng.zip -O Turkish_English_493223.zip
wget http://www.manythings.org/anki/ukr-eng.zip -O Ukrainian_English_102156.zip
wget http://www.manythings.org/anki/urd-eng.zip -O Urdu_English_1180.zip
wget http://www.manythings.org/anki/uig-eng.zip -O Uyghur_English_284.zip
wget http://www.manythings.org/anki/vie-eng.zip -O Vietnamese_English_3412.zip
wget http://www.manythings.org/anki/war-eng.zip -O Waray_English_1181.zip
